### ISSUE TITLE
Incorrect `(*strings.Builder).Write` suggestion

### ISSUE THREAD

**Issue by Juneezee** [butuzov/mirror#26]
Minimal reproducible example:

```go
package main

import "strings"

func main() {
	var strBuilder strings.Builder
	var text string = "text"
	var b byte = text[0]

	strBuilder.WriteString(string(b))
}
```

### What did I do

```
$ mirror --fix main.go
main.go:10:2: avoid allocations with (*strings.Builder).Write
```

### Expected

`strBuilder.WriteString(string(b))` is replaced by `strBuilder.WriteByte(b)`

### Actual

`mirror` replaces `strBuilder.WriteString(string(b))` with `strBuilder.Write(b)`, which is incorrect as `b` is a `byte` and `(*strings.Builder).Write` takes `[]byte`.

##### Reference

1. https://pkg.go.dev/strings#Builder.Write

2. https://pkg.go.dev/strings#Builder.WriteByte

3. https://pkg.go.dev/strings#Builder.WriteString

**Comment by butuzov** [comment]
- `(bytes.Buffer|strings.Builder).WriteByte(c byte) error` 
- `(bytes.Buffer|strings.Builder).WriteRune(r rune) (n int, err error)`

Support will be added in the near future (or whenever I have time to code).
